
#pragma kernel CSMain
#include "MarchingTable.hlsl"

RWStructuredBuffer<float> weights;

float isoLevel;
int chunkSize;
bool chunky = false;

struct Triangle 
{
    float3 a, b, c;
};

AppendStructuredBuffer<Triangle> triangles;

int indexFromCoord(int x, int y, int z)
{
    return x + chunkSize * (y + chunkSize * z);
}

float3 interp(float3 edgeVertex1, float valueAtVertex1, float3 edgeVertex2, float valueAtVertex2)
{
    return (edgeVertex1 + (isoLevel - valueAtVertex1) * (edgeVertex2 - edgeVertex1)  / (valueAtVertex2 - valueAtVertex1));
}

float3 midPoint(float3 edgeVertex1, float3 edgeVertex2)
{
    return (edgeVertex1 + edgeVertex2) / 2;
}

static const int numThreads = 8;
[numthreads(numThreads,numThreads,numThreads)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= chunkSize - 1 || id.y >= chunkSize - 1 || id.z >= chunkSize - 1)
    {
        return;
    }

    float cubeValues[8] = 
    {
       weights[indexFromCoord(id.x, id.y, id.z + 1)],
       weights[indexFromCoord(id.x + 1, id.y, id.z + 1)],
       weights[indexFromCoord(id.x + 1, id.y, id.z)],
       weights[indexFromCoord(id.x, id.y, id.z)],
       weights[indexFromCoord(id.x, id.y + 1, id.z + 1)],
       weights[indexFromCoord(id.x + 1, id.y + 1, id.z + 1)],
       weights[indexFromCoord(id.x + 1, id.y + 1, id.z)],
       weights[indexFromCoord(id.x, id.y + 1, id.z)]
    };

    int cubeIndex = 0;
    if (cubeValues[0] < isoLevel) cubeIndex |= 1;
    if (cubeValues[1] < isoLevel) cubeIndex |= 2;
    if (cubeValues[2] < isoLevel) cubeIndex |= 4;
    if (cubeValues[3] < isoLevel) cubeIndex |= 8;
    if (cubeValues[4] < isoLevel) cubeIndex |= 16;
    if (cubeValues[5] < isoLevel) cubeIndex |= 32;
    if (cubeValues[6] < isoLevel) cubeIndex |= 64;
    if (cubeValues[7] < isoLevel) cubeIndex |= 128;

    int edges[] = triTable[cubeIndex];

    for (int i = 0; edges[i] != -1; i += 3)
    {
        // First edge lies between vertex e00 and vertex e01
        int e00 = edgeConnections[edges[i]][0];
        int e01 = edgeConnections[edges[i]][1];

        // Second edge lies between vertex e10 and vertex e11
        int e10 = edgeConnections[edges[i + 1]][0];
        int e11 = edgeConnections[edges[i + 1]][1];
        
        // Third edge lies between vertex e20 and vertex e21
        int e20 = edgeConnections[edges[i + 2]][0];
        int e21 = edgeConnections[edges[i + 2]][1];

        Triangle tri;
        if(chunky)
        {
            tri.a = midPoint(cornerOffsets[e00], cornerOffsets[e01]) + id;
            tri.b = midPoint(cornerOffsets[e10], cornerOffsets[e11]) + id;
            tri.c = midPoint(cornerOffsets[e20], cornerOffsets[e21]) + id;
            
        }
        else
        {
            tri.a = interp(cornerOffsets[e00], cubeValues[e00], cornerOffsets[e01], cubeValues[e01]) + id;
            tri.b = interp(cornerOffsets[e10], cubeValues[e10], cornerOffsets[e11], cubeValues[e11]) + id;
            tri.c = interp(cornerOffsets[e20], cubeValues[e20], cornerOffsets[e21], cubeValues[e21]) + id;
        }

        triangles.Append(tri);
    }

    

}
