#pragma kernel GenerateNoise


#include "FastNoiseLite.hlsl"

static const uint numthreads = 8;

RWStructuredBuffer<float> weights;
bool is3D;
int seed;
int chunkSize;
float noiseScale;
float amplitude;
float frequency;
int octaves;
float groundPercent;
int fractalType;
int noiseType;


int offsetX;
int offsetY;
int offsetZ;

float Remap(float value, float oldMin, float oldMax, float newMin, float newMax)
{
    return (((value - oldMin) * (newMax - newMin)) / (oldMax - oldMin)) + newMin;
}

int IndexFromCoord(int x, int y, int z)
{
    return x + chunkSize * (y + chunkSize * z);
}

[numthreads(numthreads,numthreads,numthreads)]
void GenerateNoise (uint3 v : SV_DispatchThreadID)
{
    fnl_state noise = fnlCreateState(seed);
    noise.noise_type = noiseType;
    noise.fractal_type = fractalType;
    noise.frequency = frequency;
    noise.octaves = octaves;

    float3 pos = v + int3(offsetX, offsetY, offsetZ) * chunkSize;
    if(offsetX > 0 && v.x == 0) pos.x--;
    if(offsetY > 0 && v.y == 0) pos.y--;
    if(offsetZ > 0 && v.z == 0) pos.z--;

    pos *= noiseScale;

    float n;
    if(is3D)
    {
        n = fnlGetNoise3D(noise, pos.x, pos.y, pos.z) * amplitude;
    }
    else
    {
        float ground = -pos.y + (groundPercent * chunkSize);
        float maxValue = amplitude * octaves;
        n = ground + fnlGetNoise3D(noise, pos.x, pos.y, pos.z) * amplitude;
    }

    weights[IndexFromCoord(v.x, v.y, v.z)] = n;
    
}
