#pragma kernel GenerateNoise


#include "FastNoiseLite.hlsl"

static const uint numthreads = 8;

RWStructuredBuffer<float> weights;
bool is3D;
int seed;
int chunkSize;
float noiseScale;
float amplitude;
float frequency;
int octaves;
float groundPercent;
int fractalType;
int noiseType;


float offsetX;
float offsetY;
float offsetZ;

int IndexFromCoord(int x, int y, int z)
{
    return x + chunkSize * (y + chunkSize * z);
}

[numthreads(numthreads,numthreads,numthreads)]
void GenerateNoise (uint3 id : SV_DispatchThreadID)
{
    fnl_state noise = fnlCreateState(seed);
    noise.noise_type = noiseType;
    noise.fractal_type = fractalType;
    noise.frequency = frequency;
    noise.octaves = octaves;

    float3 pos = id * noiseScale;
    float n;
    if(is3D)
    {
        n = fnlGetNoise3D(noise, pos.x + offsetX, pos.y + offsetY, pos.z + offsetZ) * amplitude;
    }
    else
    {
        float ground = -pos.y + (groundPercent * chunkSize);
        n = ground + fnlGetNoise3D(noise, pos.x + offsetX, pos.y + offsetY, pos.z + offsetZ) * amplitude;
    }


    
    weights[IndexFromCoord(id.x, id.y, id.z)] = n;
    
}
